from __future__ import annotations

from dataclasses import dataclass, field
from datetime import UTC, datetime
from enum import StrEnum, auto
from pathlib import Path
from uuid import uuid4
import xml.etree.ElementTree as ET

from ix_blackfox.forge.test_runner import TestRunResult


class RegressionStatus(StrEnum):
    """
    Overall regression outcome classification.
    """

    PASSED = auto()
    FAILED = auto()
    ERROR = auto()


@dataclass(frozen=True, slots=True)
class RegressionSuiteSummary:
    """
    Summary for one JUnit test suite.
    """

    name: str
    tests: int
    failures: int
    errors: int
    skipped: int
    time_seconds: float

    def __post_init__(self) -> None:
        normalized_name = self.name.strip()
        if not normalized_name:
            raise ValueError("Regression suite name must not be empty.")
        object.__setattr__(self, "name", normalized_name)


@dataclass(frozen=True, slots=True)
class RegressionReport:
    """
    Aggregate regression report collected from a test run.
    """

    report_id: str
    created_at: datetime
    status: RegressionStatus
    framework: str
    exit_code: int
    junit_xml_path: Path
    tests: int
    failures: int
    errors: int
    skipped: int
    suites: tuple[RegressionSuiteSummary, ...] = field(default_factory=tuple)
    notes: tuple[str, ...] = field(default_factory=tuple)

    @property
    def succeeded(self) -> bool:
        """
        Return True when the regression report represents a passing result.
        """
        return self.status == RegressionStatus.PASSED

    def suite_names(self) -> tuple[str, ...]:
        """
        Return suite names in report order.
        """
        return tuple(suite.name for suite in self.suites)


class ForgeRegressionCollector:
    """
    Collector that converts test-run artifacts into normalized regression reports.

    The initial implementation consumes JUnit XML generated by the forge test
    runner and produces a stable summary for downstream verification layers.
    """

    def collect(self, test_result: TestRunResult) -> RegressionReport:
        """
        Collect regression results from one forge test run.
        """
        junit_xml_path = test_result.junit_xml_path.resolve()
        notes: list[str] = []

        if not junit_xml_path.is_file():
            notes.append("JUnit XML report is missing.")
            return RegressionReport(
                report_id=f"regr-{uuid4().hex}",
                created_at=_utc_now(),
                status=RegressionStatus.ERROR,
                framework=test_result.framework,
                exit_code=test_result.command_result.exit_code,
                junit_xml_path=junit_xml_path,
                tests=0,
                failures=0,
                errors=0,
                skipped=0,
                suites=(),
                notes=tuple(notes),
            )

        try:
            suites = _parse_junit_xml(junit_xml_path)
        except ET.ParseError as exc:
            notes.append(f"JUnit XML could not be parsed: {exc}.")
            return RegressionReport(
                report_id=f"regr-{uuid4().hex}",
                created_at=_utc_now(),
                status=RegressionStatus.ERROR,
                framework=test_result.framework,
                exit_code=test_result.command_result.exit_code,
                junit_xml_path=junit_xml_path,
                tests=0,
                failures=0,
                errors=0,
                skipped=0,
                suites=(),
                notes=tuple(notes),
            )

        tests = sum(suite.tests for suite in suites)
        failures = sum(suite.failures for suite in suites)
        errors = sum(suite.errors for suite in suites)
        skipped = sum(suite.skipped for suite in suites)

        status = _status_from_result(
            exit_code=test_result.command_result.exit_code,
            failures=failures,
            errors=errors,
        )

        if not suites:
            notes.append("JUnit XML contained no test suites.")

        return RegressionReport(
            report_id=f"regr-{uuid4().hex}",
            created_at=_utc_now(),
            status=status,
            framework=test_result.framework,
            exit_code=test_result.command_result.exit_code,
            junit_xml_path=junit_xml_path,
            tests=tests,
            failures=failures,
            errors=errors,
            skipped=skipped,
            suites=suites,
            notes=tuple(notes),
        )


def _parse_junit_xml(path: Path) -> tuple[RegressionSuiteSummary, ...]:
    tree = ET.parse(path)
    root = tree.getroot()

    suite_elements: list[ET.Element]
    if root.tag == "testsuite":
        suite_elements = [root]
    else:
        suite_elements = [element for element in root.iter("testsuite")]

    suites: list[RegressionSuiteSummary] = []
    for element in suite_elements:
        suites.append(
            RegressionSuiteSummary(
                name=_suite_name(element),
                tests=_int_attr(element, "tests"),
                failures=_int_attr(element, "failures"),
                errors=_int_attr(element, "errors"),
                skipped=_int_attr(element, "skipped"),
                time_seconds=_float_attr(element, "time"),
            )
        )

    return tuple(suites)


def _suite_name(element: ET.Element) -> str:
    raw_name = element.attrib.get("name", "").strip()
    return raw_name or "unnamed-suite"


def _int_attr(element: ET.Element, attribute: str) -> int:
    raw_value = element.attrib.get(attribute, "0").strip()
    if not raw_value:
        return 0
    return int(raw_value)


def _float_attr(element: ET.Element, attribute: str) -> float:
    raw_value = element.attrib.get(attribute, "0").strip()
    if not raw_value:
        return 0.0
    return float(raw_value)


def _status_from_result(
    *,
    exit_code: int,
    failures: int,
    errors: int,
) -> RegressionStatus:
    if exit_code == 0 and failures == 0 and errors == 0:
        return RegressionStatus.PASSED
    if errors > 0:
        return RegressionStatus.ERROR
    return RegressionStatus.FAILED


def _utc_now() -> datetime:
    return datetime.now(tz=UTC)
