"""
Repository-intelligence primitives for IX-BlackFox Wave 8.

The repository package builds deterministic, reviewable evidence about a
workspace before model-assisted code-change decisions are trusted. The first
Wave 8 layers expose stable model contracts, deterministic inventory scanning,
conservative Python AST graph extraction, dependency mapping, source-test
coverage/subsystem inference, digestable architectural memory, conservative
impact analysis, and digest-chained repository evidence.
"""

from __future__ import annotations

from ix_blackfox.repository.architecture_memory import (
    ArchitectureMemorySnapshot,
    architecture_memory_summary,
    architecture_records_by_subsystem,
    architecture_records_for_path,
    build_architecture_memory,
    default_architecture_records,
    discovered_architecture_records,
    owned_paths_from_records,
    validate_architecture_memory,
)
from ix_blackfox.repository.coverage_map import (
    RepositoryCoverageMap,
    RepositoryCoverageMapper,
    RepositorySubsystemRecord,
    build_coverage_map,
    direct_test_candidates,
    graph_based_links,
    infer_source_test_links,
    infer_subsystem_id,
    infer_subsystem_records,
    module_path_lookup,
    owned_paths_for_subsystem,
    source_module_test_candidates,
    stem_match_candidates,
)
from ix_blackfox.repository.dependencies import (
    RepositoryDependencyMapper,
    build_dependency_map,
    dependencies_from_pyproject,
    dependencies_from_workflows,
    dependency_name_from_requirement,
    external_import_dependencies,
    internal_import_edges,
    sensitive_dependency_paths,
)
from ix_blackfox.repository.evidence import (
    WAVE8_REQUIRED_EVENT_SEQUENCE,
    RepositoryEvidenceEventType,
    RepositoryEvidenceLedger,
    RepositoryEvidenceReceipt,
    RepositoryEvidenceSnapshot,
    build_repository_evidence_snapshot,
    receipt_id_for_event,
    repository_evidence_summary,
    validate_repository_evidence_snapshot,
)
from ix_blackfox.repository.impact import (
    RepositoryImpactAnalyzer,
    analyze_repository_impact,
    build_recommended_commands,
    cross_subsystem_findings,
    deduplicate_commands,
    deduplicate_findings,
    dependency_impacted_paths,
    path_basename,
    path_requires_compile_check,
    role_findings,
    sensitivity_findings,
    snapshot_records_by_path,
    tests_impacted_by_record,
    unknown_path_findings,
    unmapped_test_findings,
)
from ix_blackfox.repository.inventory import (
    RepositoryInventoryScanner,
    build_file_record,
    classify_generated_reason,
    classify_repository_file,
    classify_repository_sensitivity,
    hash_file,
    is_text_repository_file,
    scan_repository,
)
from ix_blackfox.repository.models import (
    RepositoryArchitectureRecord,
    RepositoryCodeGraph,
    RepositoryCoverageLink,
    RepositoryDependencyMap,
    RepositoryDependencyRecord,
    RepositoryDependencyScope,
    RepositoryEdgeKind,
    RepositoryFileRecord,
    RepositoryFileRole,
    RepositoryGraphEdge,
    RepositoryImpactFinding,
    RepositoryImpactReport,
    RepositoryImpactSeverity,
    RepositoryNodeKind,
    RepositorySensitivity,
    RepositorySnapshot,
    RepositorySymbolRecord,
    digest_payload,
)
from ix_blackfox.repository.python_graph import (
    PythonCodeGraphBuilder,
    assignment_target_names,
    build_python_code_graph,
    decorator_names,
    dotted_name,
    extract_constant_symbols,
    extract_method_symbols,
    extract_python_import_edges,
    extract_python_symbols,
    is_internal_module,
    module_name_from_path,
    resolve_from_import_module,
    resolve_imported_module,
)

__all__ = [
    "ArchitectureMemorySnapshot",
    "PythonCodeGraphBuilder",
    "RepositoryArchitectureRecord",
    "RepositoryCodeGraph",
    "RepositoryCoverageLink",
    "RepositoryCoverageMap",
    "RepositoryCoverageMapper",
    "RepositoryDependencyMap",
    "RepositoryDependencyMapper",
    "RepositoryDependencyRecord",
    "RepositoryDependencyScope",
    "RepositoryEdgeKind",
    "RepositoryEvidenceEventType",
    "RepositoryEvidenceLedger",
    "RepositoryEvidenceReceipt",
    "RepositoryEvidenceSnapshot",
    "RepositoryFileRecord",
    "RepositoryFileRole",
    "RepositoryGraphEdge",
    "RepositoryImpactAnalyzer",
    "RepositoryImpactFinding",
    "RepositoryImpactReport",
    "RepositoryImpactSeverity",
    "RepositoryInventoryScanner",
    "RepositoryNodeKind",
    "RepositorySensitivity",
    "RepositorySnapshot",
    "RepositorySubsystemRecord",
    "RepositorySymbolRecord",
    "WAVE8_REQUIRED_EVENT_SEQUENCE",
    "analyze_repository_impact",
    "architecture_memory_summary",
    "architecture_records_by_subsystem",
    "architecture_records_for_path",
    "assignment_target_names",
    "build_architecture_memory",
    "build_coverage_map",
    "build_dependency_map",
    "build_file_record",
    "build_python_code_graph",
    "build_recommended_commands",
    "build_repository_evidence_snapshot",
    "classify_generated_reason",
    "classify_repository_file",
    "classify_repository_sensitivity",
    "cross_subsystem_findings",
    "decorator_names",
    "deduplicate_commands",
    "deduplicate_findings",
    "default_architecture_records",
    "dependencies_from_pyproject",
    "dependencies_from_workflows",
    "dependency_impacted_paths",
    "dependency_name_from_requirement",
    "digest_payload",
    "direct_test_candidates",
    "discovered_architecture_records",
    "dotted_name",
    "external_import_dependencies",
    "extract_constant_symbols",
    "extract_method_symbols",
    "extract_python_import_edges",
    "extract_python_symbols",
    "graph_based_links",
    "hash_file",
    "infer_source_test_links",
    "infer_subsystem_id",
    "infer_subsystem_records",
    "internal_import_edges",
    "is_internal_module",
    "is_text_repository_file",
    "module_name_from_path",
    "module_path_lookup",
    "owned_paths_for_subsystem",
    "owned_paths_from_records",
    "path_basename",
    "path_requires_compile_check",
    "receipt_id_for_event",
    "repository_evidence_summary",
    "resolve_from_import_module",
    "resolve_imported_module",
    "role_findings",
    "scan_repository",
    "sensitive_dependency_paths",
    "sensitivity_findings",
    "snapshot_records_by_path",
    "source_module_test_candidates",
    "stem_match_candidates",
    "tests_impacted_by_record",
    "unknown_path_findings",
    "unmapped_test_findings",
    "validate_architecture_memory",
    "validate_repository_evidence_snapshot",
]
