"""
Repository-intelligence primitives for IX-BlackFox Wave 8.

The repository package builds deterministic, reviewable evidence about a
workspace before model-assisted code-change decisions are trusted. The first
Wave 8 layers expose stable model contracts, deterministic inventory scanning,
conservative Python AST graph extraction, dependency mapping, and source-test
coverage/subsystem inference without importing repository code.
"""

from __future__ import annotations

from ix_blackfox.repository.coverage_map import (
    RepositoryCoverageMap,
    RepositoryCoverageMapper,
    RepositorySubsystemRecord,
    build_coverage_map,
    direct_test_candidates,
    graph_based_links,
    infer_source_test_links,
    infer_subsystem_id,
    infer_subsystem_records,
    module_path_lookup,
    owned_paths_for_subsystem,
    source_module_test_candidates,
    stem_match_candidates,
)
from ix_blackfox.repository.dependencies import (
    RepositoryDependencyMapper,
    build_dependency_map,
    dependencies_from_pyproject,
    dependencies_from_workflows,
    dependency_name_from_requirement,
    external_import_dependencies,
    internal_import_edges,
    sensitive_dependency_paths,
)
from ix_blackfox.repository.inventory import (
    RepositoryInventoryScanner,
    build_file_record,
    classify_generated_reason,
    classify_repository_file,
    classify_repository_sensitivity,
    hash_file,
    is_text_repository_file,
    scan_repository,
)
from ix_blackfox.repository.models import (
    RepositoryArchitectureRecord,
    RepositoryCodeGraph,
    RepositoryCoverageLink,
    RepositoryDependencyMap,
    RepositoryDependencyRecord,
    RepositoryDependencyScope,
    RepositoryEdgeKind,
    RepositoryFileRecord,
    RepositoryFileRole,
    RepositoryGraphEdge,
    RepositoryImpactFinding,
    RepositoryImpactReport,
    RepositoryImpactSeverity,
    RepositoryNodeKind,
    RepositorySensitivity,
    RepositorySnapshot,
    RepositorySymbolRecord,
    digest_payload,
)
from ix_blackfox.repository.python_graph import (
    PythonCodeGraphBuilder,
    assignment_target_names,
    build_python_code_graph,
    decorator_names,
    dotted_name,
    extract_constant_symbols,
    extract_method_symbols,
    extract_python_import_edges,
    extract_python_symbols,
    is_internal_module,
    module_name_from_path,
    resolve_from_import_module,
    resolve_imported_module,
)

__all__ = [
    "PythonCodeGraphBuilder",
    "RepositoryArchitectureRecord",
    "RepositoryCodeGraph",
    "RepositoryCoverageLink",
    "RepositoryCoverageMap",
    "RepositoryCoverageMapper",
    "RepositoryDependencyMap",
    "RepositoryDependencyMapper",
    "RepositoryDependencyRecord",
    "RepositoryDependencyScope",
    "RepositoryEdgeKind",
    "RepositoryFileRecord",
    "RepositoryFileRole",
    "RepositoryGraphEdge",
    "RepositoryImpactFinding",
    "RepositoryImpactReport",
    "RepositoryImpactSeverity",
    "RepositoryInventoryScanner",
    "RepositoryNodeKind",
    "RepositorySensitivity",
    "RepositorySnapshot",
    "RepositorySubsystemRecord",
    "RepositorySymbolRecord",
    "assignment_target_names",
    "build_coverage_map",
    "build_dependency_map",
    "build_file_record",
    "build_python_code_graph",
    "classify_generated_reason",
    "classify_repository_file",
    "classify_repository_sensitivity",
    "decorator_names",
    "dependencies_from_pyproject",
    "dependencies_from_workflows",
    "dependency_name_from_requirement",
    "digest_payload",
    "direct_test_candidates",
    "dotted_name",
    "external_import_dependencies",
    "extract_constant_symbols",
    "extract_method_symbols",
    "extract_python_import_edges",
    "extract_python_symbols",
    "graph_based_links",
    "hash_file",
    "infer_source_test_links",
    "infer_subsystem_id",
    "infer_subsystem_records",
    "internal_import_edges",
    "is_internal_module",
    "is_text_repository_file",
    "module_name_from_path",
    "module_path_lookup",
    "owned_paths_for_subsystem",
    "resolve_from_import_module",
    "resolve_imported_module",
    "scan_repository",
    "sensitive_dependency_paths",
    "source_module_test_candidates",
    "stem_match_candidates",
]
