"""
Wave 10 AI engineering operating-system primitives.

The operating package is the top-level Wave 10 layer for multi-repo,
multi-team, policy-governed, measurable, replayable, and reviewable AI-assisted
engineering workflows. Commit 19 adds an end-to-end local assembly smoke path
that builds a compact ready dossier, validates report and export-pack digests,
and proves the final Wave 10 layers can be assembled without cloud upload,
network access, certification claims, or execution authority.
"""

from __future__ import annotations

from ix_blackfox.operating.assembly import (
    DEFAULT_WAVE10_REPORT_SECTION_KINDS,
    Wave10AssemblyResult,
    build_artifact_ref,
    build_minimal_review_bundle,
    build_wave10_ready_operating_dossier,
)
from ix_blackfox.operating.cloud import (
    CloudControlFinding,
    CloudControlSeverity,
    CloudExportFormat,
    CloudExportPack,
    CloudProvider,
    CloudSecurityControl,
    build_cloud_security_export_from_envelope,
    write_cloud_export_pack,
)
from ix_blackfox.operating.export import (
    ExportChannel,
    ExportControlSummary,
    ExportFormat,
    ExportPolicy,
    ExportReadiness,
    OperatingExportManifest,
    OperatingExportPack,
    build_export_pack,
    write_export_pack,
)
from ix_blackfox.operating.falsification import (
    FalsificationCampaign,
    FalsificationCampaignStatus,
    FalsificationResult,
    FalsificationScenario,
    FalsificationScenarioKind,
    FalsificationScenarioResult,
)
from ix_blackfox.operating.models import (
    WAVE10_OPERATING_SCHEMA_VERSION,
    OperatingArtifactKind,
    OperatingArtifactRef,
    OperatingDisposition,
    OperatingDomain,
    OperatingEnvelope,
    OperatingFinding,
    OperatingSeverity,
    OperatingSourceWave,
    digest_payload,
    normalize_dotted_name,
    normalize_identifier,
    normalize_optional_text,
    normalize_path_tuple,
    normalize_relative_path,
    normalize_sha256,
    normalize_text,
    unique_sorted_enum_tuple,
)
from ix_blackfox.operating.policy import (
    OperatingPolicy,
    OperatingPolicyDecision,
    OperatingPolicyEvaluation,
    OperatingPolicyRule,
    OperatingRuleEffect,
    OperatingRuleScope,
)
from ix_blackfox.operating.registry import (
    CrossRepoDependency,
    RepositoryCriticality,
    RepositoryRecord,
    RepositoryRegistry,
    TeamAuthorityBinding,
)
from ix_blackfox.operating.replay import (
    ReplayArtifact,
    ReplayDriftLevel,
    ReplayExpectation,
    ReplayManifest,
    ReplayReadiness,
    ReplayValidation,
    validate_replay_manifest,
)
from ix_blackfox.operating.report import (
    OperatingReport,
    OperatingReportSection,
    OperatingReportSectionKind,
    OperatingReportValidation,
    ReportAssemblyMode,
    validate_operating_report,
)
from ix_blackfox.operating.review_bundle import (
    ApprovalExpectation,
    ReviewBundleScope,
    ReviewBundleSection,
    ReviewBundleValidation,
    ReviewResponsibility,
    Wave10ReviewBundle,
    validate_review_bundle,
)
from ix_blackfox.operating.scorecard import (
    CoverageMetric,
    EvidenceMetric,
    MetricStatus,
    OperatingScorecard,
    PolicyMetric,
    ReplayMetric,
    ReviewMetric,
    RiskMetric,
    ScorecardMetric,
)
from ix_blackfox.operating.standards import (
    ControlFamily,
    StandardsCrosswalk,
    StandardsCrosswalkResult,
    StandardsFramework,
    StandardsMapping,
    evaluate_standards_crosswalk,
)
from ix_blackfox.operating.traceability import (
    AssuranceClaimMapping,
    ControlObjectiveMapping,
    HazardControlMapping,
    TraceabilityGraph,
    TraceabilityNode,
    TraceabilityNodeKind,
    TraceabilityValidation,
)
from ix_blackfox.operating.trust import (
    EvidenceFreshness,
    EvidenceTrustLevel,
    EvidenceTrustRecord,
    EvidenceTrustRegistry,
    EvidenceVerificationState,
)
from ix_blackfox.operating.work_packages import (
    OperatingWorkPackage,
    WorkPackageAuthority,
    WorkPackagePriority,
    WorkPackageRiskClass,
    WorkPackageStatus,
    WorkPackageValidation,
    validate_work_package,
)

__all__ = [
    "DEFAULT_WAVE10_REPORT_SECTION_KINDS",
    "WAVE10_OPERATING_SCHEMA_VERSION",
    "ApprovalExpectation",
    "AssuranceClaimMapping",
    "CloudControlFinding",
    "CloudControlSeverity",
    "CloudExportFormat",
    "CloudExportPack",
    "CloudProvider",
    "CloudSecurityControl",
    "ControlFamily",
    "ControlObjectiveMapping",
    "CoverageMetric",
    "CrossRepoDependency",
    "EvidenceFreshness",
    "EvidenceMetric",
    "EvidenceTrustLevel",
    "EvidenceTrustRecord",
    "EvidenceTrustRegistry",
    "EvidenceVerificationState",
    "ExportChannel",
    "ExportControlSummary",
    "ExportFormat",
    "ExportPolicy",
    "ExportReadiness",
    "FalsificationCampaign",
    "FalsificationCampaignStatus",
    "FalsificationResult",
    "FalsificationScenario",
    "FalsificationScenarioKind",
    "FalsificationScenarioResult",
    "HazardControlMapping",
    "MetricStatus",
    "OperatingArtifactKind",
    "OperatingArtifactRef",
    "OperatingDisposition",
    "OperatingDomain",
    "OperatingEnvelope",
    "OperatingExportManifest",
    "OperatingExportPack",
    "OperatingFinding",
    "OperatingPolicy",
    "OperatingPolicyDecision",
    "OperatingPolicyEvaluation",
    "OperatingPolicyRule",
    "OperatingReport",
    "OperatingReportSection",
    "OperatingReportSectionKind",
    "OperatingReportValidation",
    "OperatingRuleEffect",
    "OperatingRuleScope",
    "OperatingScorecard",
    "OperatingSeverity",
    "OperatingSourceWave",
    "OperatingWorkPackage",
    "PolicyMetric",
    "ReplayArtifact",
    "ReplayDriftLevel",
    "ReplayExpectation",
    "ReplayManifest",
    "ReplayMetric",
    "ReplayReadiness",
    "ReplayValidation",
    "ReportAssemblyMode",
    "RepositoryCriticality",
    "RepositoryRecord",
    "RepositoryRegistry",
    "ReviewBundleScope",
    "ReviewBundleSection",
    "ReviewBundleValidation",
    "ReviewMetric",
    "ReviewResponsibility",
    "RiskMetric",
    "ScorecardMetric",
    "StandardsCrosswalk",
    "StandardsCrosswalkResult",
    "StandardsFramework",
    "StandardsMapping",
    "TeamAuthorityBinding",
    "TraceabilityGraph",
    "TraceabilityNode",
    "TraceabilityNodeKind",
    "TraceabilityValidation",
    "Wave10AssemblyResult",
    "Wave10ReviewBundle",
    "WorkPackageAuthority",
    "WorkPackagePriority",
    "WorkPackageRiskClass",
    "WorkPackageStatus",
    "WorkPackageValidation",
    "build_artifact_ref",
    "build_cloud_security_export_from_envelope",
    "build_export_pack",
    "build_minimal_review_bundle",
    "build_wave10_ready_operating_dossier",
    "digest_payload",
    "evaluate_standards_crosswalk",
    "normalize_dotted_name",
    "normalize_identifier",
    "normalize_optional_text",
    "normalize_path_tuple",
    "normalize_relative_path",
    "normalize_sha256",
    "normalize_text",
    "unique_sorted_enum_tuple",
    "validate_operating_report",
    "validate_replay_manifest",
    "validate_review_bundle",
    "validate_work_package",
    "write_cloud_export_pack",
    "write_export_pack",
]
