"""
Wave 10 AI engineering operating-system primitives.

The operating package is the top-level Wave 10 layer for multi-repo,
multi-team, policy-governed, measurable, replayable, and reviewable AI-assisted
engineering workflows. Commit 11 adds sustainment blockers and readiness gates
so unresolved operational issues, missing artifacts, missing human review, and
unreviewed ready transitions fail closed instead of being reported as ready.
"""

from __future__ import annotations

from ix_blackfox.operating.authority import (
    ApprovalQuorum,
    OperatingTeam,
    ReviewBoard,
    ReviewDecision,
    ReviewerAuthority,
    ReviewerKind,
    SeparationOfDutiesRule,
    TeamReviewDecision,
    TeamRole,
)
from ix_blackfox.operating.campaign import (
    CampaignDependencyGraph,
    CampaignPhase,
    CampaignPhaseStatus,
    CampaignValidationReport,
    OperatingCampaign,
    normalize_optional_identifier,
)
from ix_blackfox.operating.evidence import (
    EvidenceAggregationResult,
    OperatingEvidenceInventory,
    OperatingEvidenceItem,
    WaveEvidenceRequirement,
    aggregate_audit_evidence_for_operating_layer,
    default_wave5_to_wave9_evidence_requirements,
    operating_artifact_kind_from_audit,
    operating_source_wave_from_audit,
)
from ix_blackfox.operating.models import (
    WAVE10_OPERATING_SCHEMA_VERSION,
    OperatingArtifactKind,
    OperatingArtifactRef,
    OperatingDisposition,
    OperatingDomain,
    OperatingEnvelope,
    OperatingFinding,
    OperatingSeverity,
    OperatingSourceWave,
    digest_payload,
    normalize_dotted_name,
    normalize_identifier,
    normalize_optional_text,
    normalize_path_tuple,
    normalize_relative_path,
    normalize_sha256,
    normalize_text,
    unique_sorted_enum_tuple,
)
from ix_blackfox.operating.policy import (
    OperatingControl,
    OperatingControlEffect,
    OperatingControlResult,
    OperatingControlResultStatus,
    OperatingGateDecision,
    OperatingPolicyContext,
    OperatingPolicyEvaluation,
    OperatingPolicyPack,
)
from ix_blackfox.operating.registry import (
    ManagedRepository,
    OperatingRegistry,
    RepositoryDependency,
    RepositoryDependencyKind,
    RepositoryEvidenceState,
    RepositoryPolicyBinding,
    RepositoryRiskLevel,
    RepositoryRiskSurface,
    RepositoryRole,
    normalize_identifier_tuple,
    normalize_required_controls,
    normalize_text_tuple,
)
from ix_blackfox.operating.replay import (
    ReplayCommand,
    ReplayEnvironment,
    ReplayManifest,
    ReplayStep,
    ReplayValidationResult,
)
from ix_blackfox.operating.review_bundle import (
    OperatingReviewBundle,
    ReviewBundleArtifact,
    ReviewBundleSection,
    ReviewBundleSectionKind,
    ReviewBundleValidation,
)
from ix_blackfox.operating.sustainment import (
    BlockerSeverity,
    BlockerStatus,
    OperatingBlocker,
    ReadinessGate,
    ReadinessState,
    ReadinessTransition,
    operating_severity_from_blocker,
)
from ix_blackfox.operating.traceability import (
    AssuranceClaimMapping,
    ControlObjectiveMapping,
    HazardControlMapping,
    OperatingTraceEdge,
    OperatingTraceNode,
    OperatingTraceabilityMap,
    TraceEdgeKind,
    TraceNodeKind,
)
from ix_blackfox.operating.work_packages import (
    EvidenceRequirement,
    ForbiddenAction,
    OperatingWorkPackage,
    RequiredValidation,
    RollbackRequirement,
    ValidationKind,
    WorkPackageDependency,
    WorkPackageDependencyKind,
    WorkPackageStatus,
)

__all__ = [
    "WAVE10_OPERATING_SCHEMA_VERSION",
    "ApprovalQuorum",
    "AssuranceClaimMapping",
    "BlockerSeverity",
    "BlockerStatus",
    "CampaignDependencyGraph",
    "CampaignPhase",
    "CampaignPhaseStatus",
    "CampaignValidationReport",
    "ControlObjectiveMapping",
    "EvidenceAggregationResult",
    "EvidenceRequirement",
    "ForbiddenAction",
    "HazardControlMapping",
    "ManagedRepository",
    "OperatingArtifactKind",
    "OperatingArtifactRef",
    "OperatingBlocker",
    "OperatingCampaign",
    "OperatingControl",
    "OperatingControlEffect",
    "OperatingControlResult",
    "OperatingControlResultStatus",
    "OperatingDisposition",
    "OperatingDomain",
    "OperatingEnvelope",
    "OperatingEvidenceInventory",
    "OperatingEvidenceItem",
    "OperatingFinding",
    "OperatingGateDecision",
    "OperatingPolicyContext",
    "OperatingPolicyEvaluation",
    "OperatingPolicyPack",
    "OperatingRegistry",
    "OperatingReviewBundle",
    "OperatingSeverity",
    "OperatingSourceWave",
    "OperatingTeam",
    "OperatingTraceEdge",
    "OperatingTraceNode",
    "OperatingTraceabilityMap",
    "OperatingWorkPackage",
    "ReadinessGate",
    "ReadinessState",
    "ReadinessTransition",
    "ReplayCommand",
    "ReplayEnvironment",
    "ReplayManifest",
    "ReplayStep",
    "ReplayValidationResult",
    "ReviewBundleArtifact",
    "ReviewBundleSection",
    "ReviewBundleSectionKind",
    "ReviewBundleValidation",
    "RequiredValidation",
    "ReviewBoard",
    "ReviewDecision",
    "ReviewerAuthority",
    "ReviewerKind",
    "RepositoryDependency",
    "RepositoryDependencyKind",
    "RepositoryEvidenceState",
    "RepositoryPolicyBinding",
    "RepositoryRiskLevel",
    "RepositoryRiskSurface",
    "RepositoryRole",
    "RollbackRequirement",
    "SeparationOfDutiesRule",
    "TeamReviewDecision",
    "TeamRole",
    "TraceEdgeKind",
    "TraceNodeKind",
    "ValidationKind",
    "WaveEvidenceRequirement",
    "WorkPackageDependency",
    "WorkPackageDependencyKind",
    "WorkPackageStatus",
    "aggregate_audit_evidence_for_operating_layer",
    "default_wave5_to_wave9_evidence_requirements",
    "digest_payload",
    "normalize_dotted_name",
    "normalize_identifier",
    "normalize_identifier_tuple",
    "normalize_optional_identifier",
    "normalize_optional_text",
    "normalize_path_tuple",
    "normalize_relative_path",
    "normalize_required_controls",
    "normalize_sha256",
    "normalize_text",
    "normalize_text_tuple",
    "operating_artifact_kind_from_audit",
    "operating_severity_from_blocker",
    "operating_source_wave_from_audit",
    "unique_sorted_enum_tuple",
]
