"""
Wave 9 audit-attestation primitives for IX-BlackFox.

The audit package models policy-pack evidence, control findings, reviewer
signoff, and explicit non-claims for DevSecOps-facing governance reports. These
primitives are deliberately bounded: they support reviewable audit readiness
inside IX-BlackFox, not certification, ATO/cATO, procurement approval, production
readiness, or autonomous authority.
"""

from __future__ import annotations

from ix_blackfox.audit.controls import (
    AuditControlEvaluation,
    AuditControlEvaluationContext,
    control_is_applicable,
    evaluate_control,
    evaluate_policy_pack,
)
from ix_blackfox.audit.evidence_bridges import (
    WAVE6_CI_REPORT_PATH,
    WAVE7_CI_REPORT_PATH,
    WAVE8_CI_REPORT_PATH,
    WAVE8_EVIDENCE_SNAPSHOT_PATH,
    KnownWaveEvidencePath,
    artifact_is_verified_by_attestation,
    bridge_pr_evidence_pack_artifacts,
    bridge_pr_evidence_pack_file,
    bridge_wave5_approval_to_signoff,
    bridge_wave5_approvals_to_signoffs,
    bridge_wave5_evidence_artifact,
    collect_known_wave_evidence,
    default_known_wave_evidence_paths,
    map_wave5_artifact_kind,
    map_wave5_attestation_kind,
    map_wave5_review_decision,
    map_wave5_reviewer_kind,
    relative_path_from_wave5_uri,
)
from ix_blackfox.audit.evidence_standard import (
    EvidenceManifestIssue,
    EvidenceManifestIssueSeverity,
    EvidenceManifestValidationResult,
    build_evidence_manifest,
    default_artifact_id,
    inspect_evidence_file,
    read_json_evidence_file,
    resolve_evidence_path,
    resolve_repo_root,
    sha256_file,
    validate_evidence_manifest,
)
from ix_blackfox.audit.models import (
    WAVE9_ATTESTATION_SUBJECT_SCHEMA_VERSION,
    WAVE9_EVIDENCE_MANIFEST_SCHEMA_VERSION,
    WAVE9_GOVERNANCE_REPORT_SCHEMA_VERSION,
    WAVE9_POLICY_PACK_SCHEMA_VERSION,
    AuditControlFinding,
    AuditControlRequirement,
    AuditControlSeverity,
    AuditControlStatus,
    AuditDisposition,
    AuditEvidenceArtifact,
    AuditEvidenceKind,
    AuditEvidenceManifest,
    AuditEvidenceSourceWave,
    AuditNonClaimSet,
    AuditReviewDecision,
    AuditReviewerKind,
    AuditReviewerSignoff,
    AuditStandardsMapping,
    AuditStandardsMappingKind,
    AuditSubject,
    derive_audit_disposition,
    digest_payload,
    normalize_head_sha,
    normalize_identifier,
    normalize_identifier_tuple,
    normalize_optional_head_sha,
    normalize_optional_text,
    normalize_path_tuple,
    normalize_relative_path,
    normalize_sha256,
    normalize_text,
    normalize_text_tuple,
)
from ix_blackfox.audit.policy_packs import (
    DEFAULT_WAVE9_POLICY_PACK_ID,
    DEFAULT_WAVE9_POLICY_PACK_TITLE,
    DEFAULT_WAVE9_POLICY_PACK_VERSION,
    AuditPolicyPack,
    default_wave9_policy_pack,
)

__all__ = [
    "DEFAULT_WAVE9_POLICY_PACK_ID",
    "DEFAULT_WAVE9_POLICY_PACK_TITLE",
    "DEFAULT_WAVE9_POLICY_PACK_VERSION",
    "WAVE6_CI_REPORT_PATH",
    "WAVE7_CI_REPORT_PATH",
    "WAVE8_CI_REPORT_PATH",
    "WAVE8_EVIDENCE_SNAPSHOT_PATH",
    "WAVE9_ATTESTATION_SUBJECT_SCHEMA_VERSION",
    "WAVE9_EVIDENCE_MANIFEST_SCHEMA_VERSION",
    "WAVE9_GOVERNANCE_REPORT_SCHEMA_VERSION",
    "WAVE9_POLICY_PACK_SCHEMA_VERSION",
    "AuditControlFinding",
    "AuditControlEvaluationContext",
    "AuditControlEvaluation",
    "AuditControlRequirement",
    "AuditControlSeverity",
    "AuditControlStatus",
    "AuditDisposition",
    "AuditEvidenceArtifact",
    "AuditEvidenceKind",
    "AuditEvidenceManifest",
    "AuditEvidenceSourceWave",
    "AuditNonClaimSet",
    "AuditPolicyPack",
    "AuditReviewDecision",
    "AuditReviewerKind",
    "AuditReviewerSignoff",
    "AuditStandardsMapping",
    "AuditStandardsMappingKind",
    "AuditSubject",
    "EvidenceManifestIssue",
    "EvidenceManifestIssueSeverity",
    "EvidenceManifestValidationResult",
    "KnownWaveEvidencePath",
    "artifact_is_verified_by_attestation",
    "bridge_pr_evidence_pack_artifacts",
    "bridge_pr_evidence_pack_file",
    "bridge_wave5_approval_to_signoff",
    "bridge_wave5_approvals_to_signoffs",
    "bridge_wave5_evidence_artifact",
    "build_evidence_manifest",
    "collect_known_wave_evidence",
    "default_artifact_id",
    "default_known_wave_evidence_paths",
    "default_wave9_policy_pack",
    "evaluate_policy_pack",
    "evaluate_control",
    "control_is_applicable",
    "derive_audit_disposition",
    "digest_payload",
    "inspect_evidence_file",
    "map_wave5_artifact_kind",
    "map_wave5_attestation_kind",
    "map_wave5_review_decision",
    "map_wave5_reviewer_kind",
    "normalize_head_sha",
    "normalize_identifier",
    "normalize_identifier_tuple",
    "normalize_optional_head_sha",
    "normalize_optional_text",
    "normalize_path_tuple",
    "normalize_relative_path",
    "normalize_sha256",
    "normalize_text",
    "normalize_text_tuple",
    "read_json_evidence_file",
    "relative_path_from_wave5_uri",
    "resolve_evidence_path",
    "resolve_repo_root",
    "sha256_file",
    "validate_evidence_manifest",
]
