"""
Wave 9 audit-attestation primitives for IX-BlackFox.

The audit package models policy-pack evidence, control findings, reviewer
signoff, and explicit non-claims for DevSecOps-facing governance reports. These
primitives are deliberately bounded: they support reviewable audit readiness
inside IX-BlackFox, not certification, ATO/cATO, procurement approval, production
readiness, or autonomous authority.
"""

from __future__ import annotations

from ix_blackfox.audit.evidence_standard import (
    EvidenceManifestIssue,
    EvidenceManifestIssueSeverity,
    EvidenceManifestValidationResult,
    build_evidence_manifest,
    default_artifact_id,
    inspect_evidence_file,
    read_json_evidence_file,
    resolve_evidence_path,
    resolve_repo_root,
    sha256_file,
    validate_evidence_manifest,
)
from ix_blackfox.audit.models import (
    WAVE9_ATTESTATION_SUBJECT_SCHEMA_VERSION,
    WAVE9_EVIDENCE_MANIFEST_SCHEMA_VERSION,
    WAVE9_GOVERNANCE_REPORT_SCHEMA_VERSION,
    WAVE9_POLICY_PACK_SCHEMA_VERSION,
    AuditControlFinding,
    AuditControlRequirement,
    AuditControlSeverity,
    AuditControlStatus,
    AuditDisposition,
    AuditEvidenceArtifact,
    AuditEvidenceKind,
    AuditEvidenceManifest,
    AuditEvidenceSourceWave,
    AuditNonClaimSet,
    AuditReviewDecision,
    AuditReviewerKind,
    AuditReviewerSignoff,
    AuditStandardsMapping,
    AuditStandardsMappingKind,
    AuditSubject,
    derive_audit_disposition,
    digest_payload,
    normalize_head_sha,
    normalize_identifier,
    normalize_identifier_tuple,
    normalize_optional_head_sha,
    normalize_optional_text,
    normalize_path_tuple,
    normalize_relative_path,
    normalize_sha256,
    normalize_text,
    normalize_text_tuple,
)
from ix_blackfox.audit.policy_packs import (
    DEFAULT_WAVE9_POLICY_PACK_ID,
    DEFAULT_WAVE9_POLICY_PACK_TITLE,
    DEFAULT_WAVE9_POLICY_PACK_VERSION,
    AuditPolicyPack,
    default_wave9_policy_pack,
)

__all__ = [
    "DEFAULT_WAVE9_POLICY_PACK_ID",
    "DEFAULT_WAVE9_POLICY_PACK_TITLE",
    "DEFAULT_WAVE9_POLICY_PACK_VERSION",
    "WAVE9_ATTESTATION_SUBJECT_SCHEMA_VERSION",
    "WAVE9_EVIDENCE_MANIFEST_SCHEMA_VERSION",
    "WAVE9_GOVERNANCE_REPORT_SCHEMA_VERSION",
    "WAVE9_POLICY_PACK_SCHEMA_VERSION",
    "AuditControlFinding",
    "AuditControlRequirement",
    "AuditControlSeverity",
    "AuditControlStatus",
    "AuditDisposition",
    "AuditEvidenceArtifact",
    "AuditEvidenceKind",
    "AuditEvidenceManifest",
    "AuditEvidenceSourceWave",
    "AuditNonClaimSet",
    "AuditPolicyPack",
    "AuditReviewDecision",
    "AuditReviewerKind",
    "AuditReviewerSignoff",
    "AuditStandardsMapping",
    "AuditStandardsMappingKind",
    "AuditSubject",
    "EvidenceManifestIssue",
    "EvidenceManifestIssueSeverity",
    "EvidenceManifestValidationResult",
    "build_evidence_manifest",
    "default_artifact_id",
    "default_wave9_policy_pack",
    "derive_audit_disposition",
    "digest_payload",
    "inspect_evidence_file",
    "normalize_head_sha",
    "normalize_identifier",
    "normalize_identifier_tuple",
    "normalize_optional_head_sha",
    "normalize_optional_text",
    "normalize_path_tuple",
    "normalize_relative_path",
    "normalize_sha256",
    "normalize_text",
    "normalize_text_tuple",
    "read_json_evidence_file",
    "resolve_evidence_path",
    "resolve_repo_root",
    "sha256_file",
    "validate_evidence_manifest",
]
