"""Wave 13 human-machine review board for IX-BlackFox.

Wave 13 consumes a verified Wave 12 assurance package, exposes non-authoritative
machine advisories, records role-specific human decisions, preserves conflicts,
recusals and evidence challenges, and evaluates a fail-closed human quorum.
Machine output never contributes approval authority.
"""

from __future__ import annotations

from ix_blackfox.review_board.admission import Wave12Admission, admit_wave12_package
from ix_blackfox.review_board.models import (
    WAVE13_CHALLENGE_SCHEMA_VERSION,
    WAVE13_EVALUATION_SCHEMA_VERSION,
    WAVE13_EXTERNAL_VERIFICATION_SCHEMA_VERSION,
    WAVE13_HUMAN_REVIEW_SCHEMA_VERSION,
    WAVE13_MACHINE_ADVISORY_SCHEMA_VERSION,
    WAVE13_POLICY_SCHEMA_VERSION,
    WAVE13_REVIEW_BOARD_SCHEMA_VERSION,
    WAVE13_SUBJECT_SCHEMA_VERSION,
    EvidenceChallenge,
    EvidenceChallengeStatus,
    ExternalHumanReviewVerification,
    HumanReview,
    HumanReviewDecision,
    MachineAdvisory,
    MachineRecommendation,
    ReviewAuthenticationState,
    ReviewBoardEvaluation,
    ReviewBoardFinding,
    ReviewBoardFindingCode,
    ReviewBoardPolicy,
    ReviewBoardStatus,
    ReviewBoardSubject,
    ReviewRole,
)
from ix_blackfox.review_board.package import (
    UPSTREAM_WAVE12_ENTRY,
    WAVE13_ADVISORY_SET_SCHEMA_VERSION,
    WAVE13_BUNDLE_INDEX_SCHEMA_VERSION,
    WAVE13_CASE_SCHEMA_VERSION,
    WAVE13_CHALLENGE_SET_SCHEMA_VERSION,
    WAVE13_HUMAN_REVIEW_SET_SCHEMA_VERSION,
    WAVE13_LEDGER_SCHEMA_VERSION,
    ReviewBoardPackageBuildResult,
    build_challenge_set,
    build_human_review_set,
    build_machine_advisory_set,
    build_review_board_package,
    build_review_bundle_index,
    build_review_case,
    build_review_ledger,
)
from ix_blackfox.review_board.policy import (
    DEFAULT_WAVE13_POLICY_ID,
    DEFAULT_WAVE13_POLICY_VERSION,
    build_machine_advisory,
    default_wave13_review_policy,
    evaluate_review_board,
)
from ix_blackfox.review_board.verify import (
    WAVE13_VERIFICATION_SCHEMA_VERSION,
    ReviewBoardPackageVerification,
    ReviewBoardVerificationIssue,
    ReviewBoardVerificationIssueCode,
    verify_review_board_package,
    write_review_board_verification,
)

__all__ = [
    "DEFAULT_WAVE13_POLICY_ID",
    "DEFAULT_WAVE13_POLICY_VERSION",
    "UPSTREAM_WAVE12_ENTRY",
    "WAVE13_ADVISORY_SET_SCHEMA_VERSION",
    "WAVE13_BUNDLE_INDEX_SCHEMA_VERSION",
    "WAVE13_CASE_SCHEMA_VERSION",
    "WAVE13_CHALLENGE_SCHEMA_VERSION",
    "WAVE13_CHALLENGE_SET_SCHEMA_VERSION",
    "WAVE13_EVALUATION_SCHEMA_VERSION",
    "WAVE13_EXTERNAL_VERIFICATION_SCHEMA_VERSION",
    "WAVE13_HUMAN_REVIEW_SCHEMA_VERSION",
    "WAVE13_HUMAN_REVIEW_SET_SCHEMA_VERSION",
    "WAVE13_LEDGER_SCHEMA_VERSION",
    "WAVE13_MACHINE_ADVISORY_SCHEMA_VERSION",
    "WAVE13_POLICY_SCHEMA_VERSION",
    "WAVE13_REVIEW_BOARD_SCHEMA_VERSION",
    "WAVE13_SUBJECT_SCHEMA_VERSION",
    "WAVE13_VERIFICATION_SCHEMA_VERSION",
    "EvidenceChallenge",
    "EvidenceChallengeStatus",
    "ExternalHumanReviewVerification",
    "HumanReview",
    "HumanReviewDecision",
    "MachineAdvisory",
    "MachineRecommendation",
    "ReviewAuthenticationState",
    "ReviewBoardEvaluation",
    "ReviewBoardFinding",
    "ReviewBoardFindingCode",
    "ReviewBoardPackageBuildResult",
    "ReviewBoardPackageVerification",
    "ReviewBoardPolicy",
    "ReviewBoardStatus",
    "ReviewBoardSubject",
    "ReviewBoardVerificationIssue",
    "ReviewBoardVerificationIssueCode",
    "ReviewRole",
    "Wave12Admission",
    "admit_wave12_package",
    "build_challenge_set",
    "build_human_review_set",
    "build_machine_advisory",
    "build_machine_advisory_set",
    "build_review_board_package",
    "build_review_bundle_index",
    "build_review_case",
    "build_review_ledger",
    "default_wave13_review_policy",
    "evaluate_review_board",
    "verify_review_board_package",
    "write_review_board_verification",
]
